server:
  port: 8080

spring:
  config:
    import: classpath:application-secret.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/issue_tracking_system
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' during development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
